/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kalkulator;


/**
 *
 * @author roagen
 */
public class Panel extends javax.swing.JFrame {
    
    /**
     * Creates new form Panel
     */
    String HISTORY = "";
    String wybrane_dzialanie = "default";
    boolean nowe = false;
    double CURRENT = 0;
    String wyswietlacz = "0";
    Ustawienia ustawienia_local;
    
    public Panel(Ustawienia ustawienia) {
        initComponents();
        
        ustawienia_local = ustawienia;
        ustawienia_local.applySettings(getContentPane());
        ustawienia_local.applySettings(jDialog1.getContentPane());
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        historia_zapisz = new javax.swing.JButton();
        historia_zamknij = new javax.swing.JButton();
        jMenuItem5 = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        klawiatura_podstawowa = new javax.swing.JPanel();
        numpad_7 = new javax.swing.JButton();
        numpad_8 = new javax.swing.JButton();
        numpad_9 = new javax.swing.JButton();
        numpad_4 = new javax.swing.JButton();
        numpad_6 = new javax.swing.JButton();
        numpad_5 = new javax.swing.JButton();
        numpad_1 = new javax.swing.JButton();
        numpad_2 = new javax.swing.JButton();
        numpad_3 = new javax.swing.JButton();
        f_show = new javax.swing.JButton();
        pm = new javax.swing.JButton();
        AC = new javax.swing.JButton();
        mnoz = new javax.swing.JButton();
        dziel = new javax.swing.JButton();
        odejmij = new javax.swing.JButton();
        dodaj = new javax.swing.JButton();
        wynik = new javax.swing.JButton();
        numpad_0 = new javax.swing.JButton();
        dot = new javax.swing.JButton();
        dodatkowe_funkcje = new javax.swing.JTabbedPane();
        klawiatura_funkcyjna = new javax.swing.JPanel();
        f_sin = new javax.swing.JButton();
        f_cos = new javax.swing.JButton();
        f_tan = new javax.swing.JButton();
        f_ln = new javax.swing.JButton();
        f_log = new javax.swing.JButton();
        f_fact = new javax.swing.JButton();
        f_inv = new javax.swing.JButton();
        f_exp = new javax.swing.JButton();
        f_cbrt = new javax.swing.JButton();
        f_sqrt = new javax.swing.JButton();
        f_pown = new javax.swing.JButton();
        f_pow2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        numerator1 = new javax.swing.JTextField();
        denominator1 = new javax.swing.JTextField();
        fraction_signs = new javax.swing.JComboBox<>();
        numerator2 = new javax.swing.JTextField();
        denominator2 = new javax.swing.JTextField();
        fraction_equals = new javax.swing.JButton();
        numerator_wynik = new javax.swing.JLabel();
        denominator_wynik = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        historia_zapisz.setText("do pliku");

        historia_zamknij.setText("zamknij");
        historia_zamknij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historia_zamknijActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addComponent(historia_zamknij)
                        .addGap(18, 18, 18)
                        .addComponent(historia_zapisz)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(historia_zamknij)
                    .addComponent(historia_zapisz))
                .addGap(19, 19, 19))
        );

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        numpad_7.setText("7");
        numpad_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpad_7ActionPerformed(evt);
            }
        });

        numpad_8.setText("8");
        numpad_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpad_8ActionPerformed(evt);
            }
        });

        numpad_9.setText("9");
        numpad_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpad_9ActionPerformed(evt);
            }
        });

        numpad_4.setText("4");
        numpad_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpad_4ActionPerformed(evt);
            }
        });

        numpad_6.setText("6");
        numpad_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpad_6ActionPerformed(evt);
            }
        });

        numpad_5.setText("5");
        numpad_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpad_5ActionPerformed(evt);
            }
        });

        numpad_1.setText("1");
        numpad_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpad_1ActionPerformed(evt);
            }
        });

        numpad_2.setText("2");
        numpad_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpad_2ActionPerformed(evt);
            }
        });

        numpad_3.setText("3");
        numpad_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpad_3ActionPerformed(evt);
            }
        });

        f_show.setText("f(x)");
        f_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_showActionPerformed(evt);
            }
        });

        pm.setText("+/-");
        pm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmActionPerformed(evt);
            }
        });

        AC.setText("AC");
        AC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACActionPerformed(evt);
            }
        });

        mnoz.setText("*");
        mnoz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnozActionPerformed(evt);
            }
        });

        dziel.setText("/");
        dziel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dzielActionPerformed(evt);
            }
        });

        odejmij.setText("-");
        odejmij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odejmijActionPerformed(evt);
            }
        });

        dodaj.setText("+");
        dodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajActionPerformed(evt);
            }
        });

        wynik.setText("=");
        wynik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wynikActionPerformed(evt);
            }
        });

        numpad_0.setText("0");
        numpad_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpad_0ActionPerformed(evt);
            }
        });

        dot.setText(".");
        dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout klawiatura_podstawowaLayout = new javax.swing.GroupLayout(klawiatura_podstawowa);
        klawiatura_podstawowa.setLayout(klawiatura_podstawowaLayout);
        klawiatura_podstawowaLayout.setHorizontalGroup(
            klawiatura_podstawowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, klawiatura_podstawowaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(klawiatura_podstawowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, klawiatura_podstawowaLayout.createSequentialGroup()
                        .addGroup(klawiatura_podstawowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, klawiatura_podstawowaLayout.createSequentialGroup()
                                .addComponent(numpad_4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numpad_5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(numpad_6))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, klawiatura_podstawowaLayout.createSequentialGroup()
                                .addComponent(numpad_7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numpad_8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(numpad_9))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, klawiatura_podstawowaLayout.createSequentialGroup()
                                .addComponent(numpad_1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numpad_2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(numpad_3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(klawiatura_podstawowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mnoz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dodaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, klawiatura_podstawowaLayout.createSequentialGroup()
                        .addComponent(numpad_0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(11, 11, 11)
                        .addComponent(wynik, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(klawiatura_podstawowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(f_show)
                    .addGroup(klawiatura_podstawowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(AC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dziel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(odejmij, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(16, 16, 16))
        );
        klawiatura_podstawowaLayout.setVerticalGroup(
            klawiatura_podstawowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(klawiatura_podstawowaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(klawiatura_podstawowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numpad_7)
                    .addComponent(numpad_8)
                    .addComponent(numpad_9)
                    .addComponent(pm)
                    .addComponent(AC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(klawiatura_podstawowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numpad_4)
                    .addComponent(numpad_6)
                    .addComponent(numpad_5)
                    .addComponent(mnoz)
                    .addComponent(dziel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(klawiatura_podstawowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numpad_1)
                    .addComponent(numpad_2)
                    .addComponent(numpad_3)
                    .addComponent(odejmij)
                    .addComponent(dodaj))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(klawiatura_podstawowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f_show)
                    .addComponent(wynik)
                    .addComponent(numpad_0)
                    .addComponent(dot))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        f_sin.setText("sin");
        f_sin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_sinActionPerformed(evt);
            }
        });

        f_cos.setText("cos");
        f_cos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_cosActionPerformed(evt);
            }
        });

        f_tan.setText("tan");
        f_tan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_tanActionPerformed(evt);
            }
        });

        f_ln.setText("ln");
        f_ln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_lnActionPerformed(evt);
            }
        });

        f_log.setText("logn");
        f_log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_logActionPerformed(evt);
            }
        });

        f_fact.setText("x!");
        f_fact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_factActionPerformed(evt);
            }
        });

        f_inv.setText("1/x");
        f_inv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_invActionPerformed(evt);
            }
        });

        f_exp.setText("exp");
        f_exp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_expActionPerformed(evt);
            }
        });

        f_cbrt.setText("cbrt");
        f_cbrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_cbrtActionPerformed(evt);
            }
        });

        f_sqrt.setText("sqrt");
        f_sqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_sqrtActionPerformed(evt);
            }
        });

        f_pown.setText("^n");
        f_pown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_pownActionPerformed(evt);
            }
        });

        f_pow2.setText("^2");
        f_pow2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_pow2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout klawiatura_funkcyjnaLayout = new javax.swing.GroupLayout(klawiatura_funkcyjna);
        klawiatura_funkcyjna.setLayout(klawiatura_funkcyjnaLayout);
        klawiatura_funkcyjnaLayout.setHorizontalGroup(
            klawiatura_funkcyjnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(klawiatura_funkcyjnaLayout.createSequentialGroup()
                .addGroup(klawiatura_funkcyjnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(f_tan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(f_sin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(f_cos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(f_ln, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(klawiatura_funkcyjnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(f_log, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(f_fact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(f_inv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(f_exp, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(klawiatura_funkcyjnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(f_cbrt, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(f_sqrt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(f_pown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(f_pow2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        klawiatura_funkcyjnaLayout.setVerticalGroup(
            klawiatura_funkcyjnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(klawiatura_funkcyjnaLayout.createSequentialGroup()
                .addGroup(klawiatura_funkcyjnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f_sin)
                    .addComponent(f_log)
                    .addComponent(f_cbrt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(klawiatura_funkcyjnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f_cos)
                    .addComponent(f_fact)
                    .addComponent(f_sqrt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(klawiatura_funkcyjnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f_tan)
                    .addComponent(f_inv)
                    .addComponent(f_pow2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(klawiatura_funkcyjnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f_ln)
                    .addComponent(f_exp)
                    .addComponent(f_pown))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        dodatkowe_funkcje.addTab("funkcje", klawiatura_funkcyjna);

        jButton1.setText("pi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("e");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("fi");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("h");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("G");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("g");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton6))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        dodatkowe_funkcje.addTab("stałe", jPanel5);

        dodatkowe_funkcje.setVisible(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(klawiatura_podstawowa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(dodatkowe_funkcje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(klawiatura_podstawowa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dodatkowe_funkcje, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("naukowy", jPanel3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 674, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 314, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("programisty", jPanel2);

        numerator1.setText("0");
        numerator1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerator1ActionPerformed(evt);
            }
        });

        denominator1.setText("1");
        denominator1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                denominator1ActionPerformed(evt);
            }
        });

        fraction_signs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-", "*" }));
        fraction_signs.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fraction_signsFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fraction_signsFocusLost(evt);
            }
        });
        fraction_signs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fraction_signsMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fraction_signsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fraction_signsMousePressed(evt);
            }
        });
        fraction_signs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fraction_signsActionPerformed(evt);
            }
        });

        numerator2.setText("0");
        numerator2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerator2ActionPerformed(evt);
            }
        });

        denominator2.setText("1");

        fraction_equals.setText("=");
        fraction_equals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fraction_equalsActionPerformed(evt);
            }
        });

        numerator_wynik.setText("0");

        denominator_wynik.setText("0");

        jButton7.setText("kopiuj wynik do 1. pola");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel3.setText("ułamki");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(numerator1, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                    .addComponent(denominator1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fraction_signs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(denominator2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(numerator2))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numerator_wynik)
                            .addComponent(denominator_wynik))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(fraction_equals)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numerator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fraction_signs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fraction_equals)))
                            .addComponent(numerator1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(denominator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(denominator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(denominator_wynik)))
                    .addComponent(numerator_wynik))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("pierwiastki");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 76, Short.MAX_VALUE))
        );

        jTextField1.setText("n");

        jTextField2.setText("k");

        jLabel4.setText("współczynnik dwumianowy Newtona");

        jButton8.setText("=");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jButton8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel4)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton8)
                        .addGap(34, 34, 34))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("inne", jPanel1);

        jMenu1.setText("Menu");

        jMenuItem1.setText("Powrót");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Wyjście");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Historia");

        jMenuItem3.setText("ostatnie działania");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("zapisz do pliku");
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Menu_glowne menu_glowne = new Menu_glowne(ustawienia_local);
        menu_glowne.show();
        this.dispose();
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void f_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_showActionPerformed
        // TODO add your handling code here:
        dodatkowe_funkcje.setVisible(!dodatkowe_funkcje.isVisible());
    }//GEN-LAST:event_f_showActionPerformed

    private void numpad_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpad_7ActionPerformed
        // TODO add your handling code here:
        do_wyswietlacza("7");
    }//GEN-LAST:event_numpad_7ActionPerformed

    private void numpad_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpad_8ActionPerformed
        // TODO add your handling code here:
        do_wyswietlacza("8");
    }//GEN-LAST:event_numpad_8ActionPerformed

    private void numpad_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpad_9ActionPerformed
        // TODO add your handling code here:
        do_wyswietlacza("9");
    }//GEN-LAST:event_numpad_9ActionPerformed

    private void numpad_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpad_4ActionPerformed
        // TODO add your handling code here:
        do_wyswietlacza("4");
    }//GEN-LAST:event_numpad_4ActionPerformed

    private void numpad_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpad_5ActionPerformed
        // TODO add your handling code here:
        do_wyswietlacza("5");
    }//GEN-LAST:event_numpad_5ActionPerformed

    private void numpad_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpad_6ActionPerformed
        // TODO add your handling code here:
        do_wyswietlacza("6");
    }//GEN-LAST:event_numpad_6ActionPerformed

    private void numpad_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpad_1ActionPerformed
        // TODO add your handling code here:
        do_wyswietlacza("1");
    }//GEN-LAST:event_numpad_1ActionPerformed

    private void numpad_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpad_2ActionPerformed
        // TODO add your handling code here:
        do_wyswietlacza("2");
    }//GEN-LAST:event_numpad_2ActionPerformed

    private void numpad_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpad_3ActionPerformed
        // TODO add your handling code here:
        do_wyswietlacza("3");
    }//GEN-LAST:event_numpad_3ActionPerformed

    private void dotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dotActionPerformed
        // TODO add your handling code here:
        do_wyswietlacza(".");
    }//GEN-LAST:event_dotActionPerformed

    private void numpad_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpad_0ActionPerformed
        // TODO add your handling code here:
        do_wyswietlacza("0");
    }//GEN-LAST:event_numpad_0ActionPerformed

    private void dodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajActionPerformed
        // TODO add your handling code here:
        wybrane_dzialanie = "dodaj";
        nowe = true;
    }//GEN-LAST:event_dodajActionPerformed

    private void odejmijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odejmijActionPerformed
        // TODO add your handling code here:
        wybrane_dzialanie = "odejmij";
        nowe = true;
    }//GEN-LAST:event_odejmijActionPerformed

    private void mnozActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnozActionPerformed
        // TODO add your handling code here:
        wybrane_dzialanie = "mnoz";
        nowe = true;
    }//GEN-LAST:event_mnozActionPerformed

    private void dzielActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dzielActionPerformed
        // TODO add your handling code here:
        wybrane_dzialanie = "dziel";
        nowe = true;
        
    }//GEN-LAST:event_dzielActionPerformed

    private void wynikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wynikActionPerformed
        // TODO add your handling code here:
        dzialanie();
    }//GEN-LAST:event_wynikActionPerformed

    private void pmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmActionPerformed
        // TODO add your handling code here:
        wyswietlacz = (-1*Double.parseDouble(wyswietlacz))+"";
        refresh();
        
    }//GEN-LAST:event_pmActionPerformed

    private void ACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACActionPerformed
        // TODO add your handling code here:
        wyswietlacz = "0";
        CURRENT = 0;
        refresh();
        
        
    }//GEN-LAST:event_ACActionPerformed

    private void f_sinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_sinActionPerformed
        // TODO add your handling code here:
        HISTORY += "sin(" + wyswietlacz + ")";
        wyswietlacz = Math.sin(Double.parseDouble(wyswietlacz)) + "";
        HISTORY += "="+wyswietlacz + "\n";
        wybrane_dzialanie = "default";
        refresh();
    }//GEN-LAST:event_f_sinActionPerformed

    private void f_cosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_cosActionPerformed
        // TODO add your handling code here:
        HISTORY += "cos(" + wyswietlacz + ")";
        wyswietlacz = Math.cos(Double.parseDouble(wyswietlacz)) + "";
        HISTORY += "="+wyswietlacz + "\n";
        wybrane_dzialanie = "default";
        refresh();
    }//GEN-LAST:event_f_cosActionPerformed

    private void f_tanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_tanActionPerformed
        // TODO add your handling code here:
        HISTORY += "tan(" + wyswietlacz + ")";
        wyswietlacz = Math.tan(Double.parseDouble(wyswietlacz)) + "";
        HISTORY += "="+wyswietlacz + "\n";
        wybrane_dzialanie = "default";
        refresh();
    }//GEN-LAST:event_f_tanActionPerformed

    private void f_lnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_lnActionPerformed
        // TODO add your handling code here:
        HISTORY += "ln(" + wyswietlacz + ")";
        wyswietlacz = Math.log(Double.parseDouble(wyswietlacz)) + "";
        HISTORY += "="+wyswietlacz + "\n";
        wybrane_dzialanie = "default";
        refresh();
    }//GEN-LAST:event_f_lnActionPerformed

    private void f_expActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_expActionPerformed
        // TODO add your handling code here:
        HISTORY += "exp(" + wyswietlacz + ")";
        wyswietlacz = Math.exp(Double.parseDouble(wyswietlacz)) + "";
        HISTORY += "="+wyswietlacz + "\n";
        wybrane_dzialanie = "default";
        refresh();
    }//GEN-LAST:event_f_expActionPerformed

    private void f_invActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_invActionPerformed
        // TODO add your handling code here:
        HISTORY += "1/(" + wyswietlacz + ")";
        wyswietlacz = 1/(Double.parseDouble(wyswietlacz)) + "";
        HISTORY += "="+wyswietlacz + "\n";
        wybrane_dzialanie = "default";
        refresh();
    }//GEN-LAST:event_f_invActionPerformed

    private void f_factActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_factActionPerformed
        // TODO add your handling code here:
        double k = Double.parseDouble(wyswietlacz);
        
        int f = 1;
        for(int i = 1; i <= k; i++){
            f *= i;
        }
        wyswietlacz = f + "";
        wybrane_dzialanie = "default";
        refresh();
          
        
        
    }//GEN-LAST:event_f_factActionPerformed

    private void f_cbrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_cbrtActionPerformed
        // TODO add your handling code here:
        HISTORY += "cbrt(" + wyswietlacz + ")";
        wyswietlacz = Math.cbrt(Double.parseDouble(wyswietlacz)) + "";
        HISTORY += "="+wyswietlacz + "\n";
        wybrane_dzialanie = "default";
        refresh();
    }//GEN-LAST:event_f_cbrtActionPerformed

    private void f_sqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_sqrtActionPerformed
        // TODO add your handling code here:
        HISTORY += "sqrt(" + wyswietlacz + ")";
        wyswietlacz = Math.sqrt(Double.parseDouble(wyswietlacz)) + "";
        HISTORY += "="+wyswietlacz + "\n";
        wybrane_dzialanie = "default";
        refresh();
    }//GEN-LAST:event_f_sqrtActionPerformed

    private void f_pow2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_pow2ActionPerformed
        // TODO add your handling code here:
        HISTORY += wyswietlacz + "^2";
        double k = Double.parseDouble(wyswietlacz);
        wyswietlacz = k*k + "";
        HISTORY += "="+wyswietlacz + "\n";
        wybrane_dzialanie = "default";
        refresh();
        
    }//GEN-LAST:event_f_pow2ActionPerformed

    private void f_pownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_pownActionPerformed
        // TODO add your handling code here:
        
        wybrane_dzialanie = "poteguj";
        nowe = true;
        
    }//GEN-LAST:event_f_pownActionPerformed

    private void f_logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_logActionPerformed
        // TODO add your handling code here:
        wybrane_dzialanie = "logarytmuj";
        nowe = true;
        
        
    }//GEN-LAST:event_f_logActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        do_wyswietlacza(Math.PI + "");
        
        refresh();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        do_wyswietlacza(Math.E + "");
        refresh();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        do_wyswietlacza((1 + Math.sqrt(5))/2 + "");
        refresh();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        do_wyswietlacza("6.6260687652");
        refresh();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        do_wyswietlacza("6.67");
        refresh();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        do_wyswietlacza("9.81");
        refresh();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void numerator1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numerator1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numerator1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        
        jDialog1.show();
        
        jTextArea1.setText(HISTORY);
        
        
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void historia_zamknijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historia_zamknijActionPerformed
        // TODO add your handling code here:
        jDialog1.dispose();
    }//GEN-LAST:event_historia_zamknijActionPerformed

    private void fraction_equalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fraction_equalsActionPerformed
        // TODO add your handling code here:
        int num1 = Integer.parseInt(numerator1.getText());
        int num2 = Integer.parseInt(numerator2.getText());
        int den1 = Integer.parseInt(denominator1.getText());
        int den2 = Integer.parseInt(denominator2.getText());
        
        int f_num = 0;
        String op = "+";
        switch(fraction_signs.getSelectedIndex()){
            case 0:
                f_num = (num1 * den2) + (num2*den1);
                op = "+";
                break;
            case 1:
                f_num = (num1 * den2) - (num2*den1);
                op = "-";
                break;
            case 2:
                f_num = num1 * num2;
                op = "*";
                break;
        }
        int f_den = den1*den2;
        
        if(!(f_num == 0 || f_den == 0)){
                int nw = NWD(Math.abs(f_num),Math.abs(f_den));
        
                f_num /= nw;
                f_den /= nw;
        
        
        }

        
        numerator_wynik.setText(f_num+"");
        denominator_wynik.setText(f_den + "");
        HISTORY+= numerator1.getText() + "/" + denominator1.getText() + op 
                + numerator2.getText() + "/" +denominator2.getText() + "=" 
                + numerator_wynik.getText() + "/" + denominator_wynik.getText()
                + "\n";
        
        
    }//GEN-LAST:event_fraction_equalsActionPerformed

    private void fraction_signsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fraction_signsActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_fraction_signsActionPerformed

    private void numerator2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numerator2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numerator2ActionPerformed

    private void denominator1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_denominator1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_denominator1ActionPerformed

    private void fraction_signsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fraction_signsMouseClicked
        // TODO add your handling code here:
    
    }//GEN-LAST:event_fraction_signsMouseClicked

    private void fraction_signsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fraction_signsMousePressed
        // TODO add your handling code here:
           
    }//GEN-LAST:event_fraction_signsMousePressed

    private void fraction_signsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fraction_signsFocusGained
        // TODO add your handling code here:
     
    }//GEN-LAST:event_fraction_signsFocusGained

    private void fraction_signsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fraction_signsFocusLost
        // TODO add your handling code here:
   
    }//GEN-LAST:event_fraction_signsFocusLost

    private void fraction_signsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fraction_signsMouseExited
   
    }//GEN-LAST:event_fraction_signsMouseExited

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        numerator1.setText(numerator_wynik.getText());
        denominator1.setText(denominator_wynik.getText());
        
    }//GEN-LAST:event_jButton7ActionPerformed
    
    public int NWD(int a, int b){
        while(a != b){
               if(a > b){
                   a -= b;
               } else {
                   b -= a;
               }
        
        }
        
        return a;
    }
    
    
    public void do_wyswietlacza(String n){
        if(nowe){
            CURRENT = Double.parseDouble(wyswietlacz);
            wyswietlacz = "";
            nowe = false;
        
        }
        
        if("default".equals(wybrane_dzialanie)){
            CURRENT = 0;
            wyswietlacz = n;
            wybrane_dzialanie = "dodaj";
        
        } else {
            wyswietlacz += n;
        }
        
        
        refresh();
        
    }
    
    public void dzialanie(){
        
        
        String symbol = "";
        HISTORY += CURRENT;
        if("dodaj".equals(wybrane_dzialanie)){
            CURRENT += Double.parseDouble(wyswietlacz);
            symbol = "+";
            
        }
        if("odejmij".equals(wybrane_dzialanie)){
            CURRENT -= Double.parseDouble(wyswietlacz);
            symbol = "-";
           
        }
        
        if("dziel".equals(wybrane_dzialanie)){
            if("0".equals(wyswietlacz)){
                CURRENT = 0;
                
                
            } else {
                CURRENT /= Double.parseDouble(wyswietlacz);
                
            }
            symbol = "/";
            
            
        }
        
        if("mnoz".equals(wybrane_dzialanie)){
            CURRENT *= Double.parseDouble(wyswietlacz);
            symbol = "*";
        
        }
        
        if("poteguj".equals(wybrane_dzialanie)){
            double k = Double.parseDouble(wyswietlacz);
            double CUR_L = CURRENT;
            for(int i = 1; i < k; i++){
                CURRENT*=CUR_L;
            }
            symbol = "^";
            
        }
        
        if("logarytmuj".equals(wybrane_dzialanie)){
            double k = Double.parseDouble(wyswietlacz);
            CURRENT = Math.log(CURRENT)/Math.log(k);
            symbol = "log";
            
            
        }
        
        HISTORY += symbol + wyswietlacz + "=" + CURRENT + "\n";
        wyswietlacz = CURRENT + "";
        wybrane_dzialanie = "default";
        refresh();
    }
    
    
    public void refresh(){
        jLabel1.setText(wyswietlacz);
    
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Ustawienia ustawienia = new Ustawienia();
                new Panel(ustawienia).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AC;
    private javax.swing.JTextField denominator1;
    private javax.swing.JTextField denominator2;
    private javax.swing.JLabel denominator_wynik;
    private javax.swing.JButton dodaj;
    private javax.swing.JTabbedPane dodatkowe_funkcje;
    private javax.swing.JButton dot;
    private javax.swing.JButton dziel;
    private javax.swing.JButton f_cbrt;
    private javax.swing.JButton f_cos;
    private javax.swing.JButton f_exp;
    private javax.swing.JButton f_fact;
    private javax.swing.JButton f_inv;
    private javax.swing.JButton f_ln;
    private javax.swing.JButton f_log;
    private javax.swing.JButton f_pow2;
    private javax.swing.JButton f_pown;
    private javax.swing.JButton f_show;
    private javax.swing.JButton f_sin;
    private javax.swing.JButton f_sqrt;
    private javax.swing.JButton f_tan;
    private javax.swing.JButton fraction_equals;
    private javax.swing.JComboBox<String> fraction_signs;
    private javax.swing.JButton historia_zamknij;
    private javax.swing.JButton historia_zapisz;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel klawiatura_funkcyjna;
    private javax.swing.JPanel klawiatura_podstawowa;
    private javax.swing.JButton mnoz;
    private javax.swing.JTextField numerator1;
    private javax.swing.JTextField numerator2;
    private javax.swing.JLabel numerator_wynik;
    private javax.swing.JButton numpad_0;
    private javax.swing.JButton numpad_1;
    private javax.swing.JButton numpad_2;
    private javax.swing.JButton numpad_3;
    private javax.swing.JButton numpad_4;
    private javax.swing.JButton numpad_5;
    private javax.swing.JButton numpad_6;
    private javax.swing.JButton numpad_7;
    private javax.swing.JButton numpad_8;
    private javax.swing.JButton numpad_9;
    private javax.swing.JButton odejmij;
    private javax.swing.JButton pm;
    private javax.swing.JButton wynik;
    // End of variables declaration//GEN-END:variables
}
