/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kalkulator;

import java.awt.Component;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author roagen
 */
public class Panel extends javax.swing.JFrame {
    
    /**
     * Creates new form Panel
     */
    String wybrane_dzialanie = "default";
    boolean nowe = false;
    double CURRENT = 0;
    String wyswietlacz = "0";
    Ustawienia ustawienia_local;
    
    public Panel(Ustawienia ustawienia) {
        initComponents();
        
        ustawienia_local = ustawienia;
        ustawienia_local.applySettings(getContentPane());
        //tło
        /*
        jTabbedPane1.setBackground(ustawienia.getBackgroundColor());
        jPanel1.setBackground(ustawienia.getBackgroundColor());
        jPanel2.setBackground(ustawienia.getBackgroundColor());
        jPanel3.setBackground(ustawienia.getBackgroundColor());
        jMenuBar1.setBackground(ustawienia.getBackgroundColor());
        klawiatura_podstawowa.setBackground(ustawienia.getBackgroundColor());
        
        //tło guzików
        
        //jTabbedPane1.getSelectedComponent().setBackground(Color.BLACK);
        //jTabbedPane1.getSelectedComponent().setForeground(Color.WHITE);
        jMenu1.setBackground(ustawienia.getButtonColor());
        jMenu2.setBackground(ustawienia.getButtonColor());
          */  
            /*
            for(Component comp : jPanel3.getComponents()){
                if(comp instanceof JButton){
                    comp.setBackground(ustawienia.getButtonColor());
                }
                
                if(comp instanceof JPanel){
                    for(Component comp_1 : ((JPanel) comp).getComponents()){
                        if(comp_1 instanceof JButton){
                            comp.setBackground(ustawienia.getButtonColor());
                        }
                    }
                }
                
                
            }
            */
        
            
            //operacje numeryczna
            /*
            AC.setBackground(ustawienia.getButtonColor());
            pm.setBackground(ustawienia.getButtonColor());
            dodaj.setBackground(ustawienia.getButtonColor());
            dot.setBackground(ustawienia.getButtonColor());
            dziel.setBackground(ustawienia.getButtonColor());
            f_show.setBackground(ustawienia.getButtonColor());
            mnoz.setBackground(ustawienia.getButtonColor());
            odejmij.setBackground(ustawienia.getButtonColor());
            wynik.setBackground(ustawienia.getButtonColor());
            numpad_0.setBackground(ustawienia.getButtonColor());
            numpad_1.setBackground(ustawienia.getButtonColor());
            numpad_2.setBackground(ustawienia.getButtonColor());
            numpad_3.setBackground(ustawienia.getButtonColor());
            numpad_4.setBackground(ustawienia.getButtonColor());
            numpad_5.setBackground(ustawienia.getButtonColor());
            numpad_6.setBackground(ustawienia.getButtonColor());
            numpad_7.setBackground(ustawienia.getButtonColor());
            numpad_8.setBackground(ustawienia.getButtonColor());
            numpad_9.setBackground(ustawienia.getButtonColor());
            f_cbrt.setBackground(ustawienia.getButtonColor());
            f_sqrt.setBackground(ustawienia.getButtonColor());
            */
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        klawiatura_podstawowa = new javax.swing.JPanel();
        numpad_7 = new javax.swing.JButton();
        numpad_8 = new javax.swing.JButton();
        numpad_9 = new javax.swing.JButton();
        numpad_4 = new javax.swing.JButton();
        numpad_6 = new javax.swing.JButton();
        numpad_5 = new javax.swing.JButton();
        numpad_1 = new javax.swing.JButton();
        numpad_2 = new javax.swing.JButton();
        numpad_3 = new javax.swing.JButton();
        f_show = new javax.swing.JButton();
        pm = new javax.swing.JButton();
        AC = new javax.swing.JButton();
        mnoz = new javax.swing.JButton();
        dziel = new javax.swing.JButton();
        odejmij = new javax.swing.JButton();
        dodaj = new javax.swing.JButton();
        wynik = new javax.swing.JButton();
        numpad_0 = new javax.swing.JButton();
        dot = new javax.swing.JButton();
        dodatkowe_funkcje = new javax.swing.JTabbedPane();
        klawiatura_funkcyjna = new javax.swing.JPanel();
        f_sin = new javax.swing.JButton();
        f_cos = new javax.swing.JButton();
        f_tan = new javax.swing.JButton();
        f_ln = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        f_fact = new javax.swing.JButton();
        f_inv = new javax.swing.JButton();
        f_exp = new javax.swing.JButton();
        f_cbrt = new javax.swing.JButton();
        f_sqrt = new javax.swing.JButton();
        f_pown = new javax.swing.JButton();
        f_pow2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jToggleButton16 = new javax.swing.JToggleButton();
        jToggleButton17 = new javax.swing.JToggleButton();
        jToggleButton18 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        numpad_7.setText("7");
        numpad_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpad_7ActionPerformed(evt);
            }
        });

        numpad_8.setText("8");
        numpad_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpad_8ActionPerformed(evt);
            }
        });

        numpad_9.setText("9");
        numpad_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpad_9ActionPerformed(evt);
            }
        });

        numpad_4.setText("4");
        numpad_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpad_4ActionPerformed(evt);
            }
        });

        numpad_6.setText("6");
        numpad_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpad_6ActionPerformed(evt);
            }
        });

        numpad_5.setText("5");
        numpad_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpad_5ActionPerformed(evt);
            }
        });

        numpad_1.setText("1");
        numpad_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpad_1ActionPerformed(evt);
            }
        });

        numpad_2.setText("2");
        numpad_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpad_2ActionPerformed(evt);
            }
        });

        numpad_3.setText("3");
        numpad_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpad_3ActionPerformed(evt);
            }
        });

        f_show.setText("f(x)");
        f_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_showActionPerformed(evt);
            }
        });

        pm.setText("+/-");
        pm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmActionPerformed(evt);
            }
        });

        AC.setText("AC");
        AC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACActionPerformed(evt);
            }
        });

        mnoz.setText("*");
        mnoz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnozActionPerformed(evt);
            }
        });

        dziel.setText("/");
        dziel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dzielActionPerformed(evt);
            }
        });

        odejmij.setText("-");
        odejmij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odejmijActionPerformed(evt);
            }
        });

        dodaj.setText("+");
        dodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajActionPerformed(evt);
            }
        });

        wynik.setText("=");
        wynik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wynikActionPerformed(evt);
            }
        });

        numpad_0.setText("0");
        numpad_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpad_0ActionPerformed(evt);
            }
        });

        dot.setText(".");
        dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout klawiatura_podstawowaLayout = new javax.swing.GroupLayout(klawiatura_podstawowa);
        klawiatura_podstawowa.setLayout(klawiatura_podstawowaLayout);
        klawiatura_podstawowaLayout.setHorizontalGroup(
            klawiatura_podstawowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, klawiatura_podstawowaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(klawiatura_podstawowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, klawiatura_podstawowaLayout.createSequentialGroup()
                        .addGroup(klawiatura_podstawowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, klawiatura_podstawowaLayout.createSequentialGroup()
                                .addComponent(numpad_4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numpad_5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(numpad_6))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, klawiatura_podstawowaLayout.createSequentialGroup()
                                .addComponent(numpad_7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numpad_8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(numpad_9))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, klawiatura_podstawowaLayout.createSequentialGroup()
                                .addComponent(numpad_1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numpad_2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(numpad_3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(klawiatura_podstawowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mnoz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dodaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, klawiatura_podstawowaLayout.createSequentialGroup()
                        .addComponent(numpad_0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(11, 11, 11)
                        .addComponent(wynik, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(klawiatura_podstawowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(f_show)
                    .addGroup(klawiatura_podstawowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(AC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dziel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(odejmij, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(16, 16, 16))
        );
        klawiatura_podstawowaLayout.setVerticalGroup(
            klawiatura_podstawowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(klawiatura_podstawowaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(klawiatura_podstawowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numpad_7)
                    .addComponent(numpad_8)
                    .addComponent(numpad_9)
                    .addComponent(pm)
                    .addComponent(AC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(klawiatura_podstawowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numpad_4)
                    .addComponent(numpad_6)
                    .addComponent(numpad_5)
                    .addComponent(mnoz)
                    .addComponent(dziel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(klawiatura_podstawowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numpad_1)
                    .addComponent(numpad_2)
                    .addComponent(numpad_3)
                    .addComponent(odejmij)
                    .addComponent(dodaj))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(klawiatura_podstawowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f_show)
                    .addComponent(wynik)
                    .addComponent(numpad_0)
                    .addComponent(dot))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        f_sin.setText("sin");
        f_sin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_sinActionPerformed(evt);
            }
        });

        f_cos.setText("cos");
        f_cos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_cosActionPerformed(evt);
            }
        });

        f_tan.setText("tan");
        f_tan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_tanActionPerformed(evt);
            }
        });

        f_ln.setText("ln");
        f_ln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_lnActionPerformed(evt);
            }
        });

        jButton8.setText("log");

        f_fact.setText("x!");
        f_fact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_factActionPerformed(evt);
            }
        });

        f_inv.setText("1/x");
        f_inv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_invActionPerformed(evt);
            }
        });

        f_exp.setText("exp");
        f_exp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_expActionPerformed(evt);
            }
        });

        f_cbrt.setText("cbrt");
        f_cbrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_cbrtActionPerformed(evt);
            }
        });

        f_sqrt.setText("sqrt");
        f_sqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_sqrtActionPerformed(evt);
            }
        });

        f_pown.setText("^n");

        f_pow2.setText("^2");
        f_pow2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_pow2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout klawiatura_funkcyjnaLayout = new javax.swing.GroupLayout(klawiatura_funkcyjna);
        klawiatura_funkcyjna.setLayout(klawiatura_funkcyjnaLayout);
        klawiatura_funkcyjnaLayout.setHorizontalGroup(
            klawiatura_funkcyjnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(klawiatura_funkcyjnaLayout.createSequentialGroup()
                .addGroup(klawiatura_funkcyjnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(f_tan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(f_sin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(f_cos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(f_ln, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(klawiatura_funkcyjnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(f_fact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(f_inv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(f_exp, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(klawiatura_funkcyjnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(f_cbrt, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(f_sqrt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(f_pown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(f_pow2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        klawiatura_funkcyjnaLayout.setVerticalGroup(
            klawiatura_funkcyjnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(klawiatura_funkcyjnaLayout.createSequentialGroup()
                .addGroup(klawiatura_funkcyjnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f_sin)
                    .addComponent(jButton8)
                    .addComponent(f_cbrt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(klawiatura_funkcyjnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f_cos)
                    .addComponent(f_fact)
                    .addComponent(f_sqrt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(klawiatura_funkcyjnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f_tan)
                    .addComponent(f_inv)
                    .addComponent(f_pow2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(klawiatura_funkcyjnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f_ln)
                    .addComponent(f_exp)
                    .addComponent(f_pown))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        dodatkowe_funkcje.addTab("funkcje", klawiatura_funkcyjna);

        jToggleButton16.setText("e");

        jToggleButton17.setText("pi");

        jToggleButton18.setText("fi");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToggleButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButton17, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                    .addComponent(jToggleButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButton16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButton17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButton18)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        dodatkowe_funkcje.addTab("stałe", jPanel5);

        dodatkowe_funkcje.setVisible(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(klawiatura_podstawowa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(dodatkowe_funkcje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(klawiatura_podstawowa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dodatkowe_funkcje, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("naukowy", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 702, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 233, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("ułamków", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 702, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 233, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("programisty", jPanel2);

        jMenu1.setText("Menu");

        jMenuItem1.setText("Powrót");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Wyjście");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Pomoc");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Menu_glowne menu_glowne = new Menu_glowne(ustawienia_local);
        menu_glowne.show();
        this.dispose();
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void f_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_showActionPerformed
        // TODO add your handling code here:
        dodatkowe_funkcje.setVisible(!dodatkowe_funkcje.isVisible());
    }//GEN-LAST:event_f_showActionPerformed

    private void numpad_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpad_7ActionPerformed
        // TODO add your handling code here:
        do_wyswietlacza("7");
    }//GEN-LAST:event_numpad_7ActionPerformed

    private void numpad_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpad_8ActionPerformed
        // TODO add your handling code here:
        do_wyswietlacza("8");
    }//GEN-LAST:event_numpad_8ActionPerformed

    private void numpad_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpad_9ActionPerformed
        // TODO add your handling code here:
        do_wyswietlacza("9");
    }//GEN-LAST:event_numpad_9ActionPerformed

    private void numpad_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpad_4ActionPerformed
        // TODO add your handling code here:
        do_wyswietlacza("4");
    }//GEN-LAST:event_numpad_4ActionPerformed

    private void numpad_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpad_5ActionPerformed
        // TODO add your handling code here:
        do_wyswietlacza("5");
    }//GEN-LAST:event_numpad_5ActionPerformed

    private void numpad_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpad_6ActionPerformed
        // TODO add your handling code here:
        do_wyswietlacza("6");
    }//GEN-LAST:event_numpad_6ActionPerformed

    private void numpad_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpad_1ActionPerformed
        // TODO add your handling code here:
        do_wyswietlacza("1");
    }//GEN-LAST:event_numpad_1ActionPerformed

    private void numpad_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpad_2ActionPerformed
        // TODO add your handling code here:
        do_wyswietlacza("2");
    }//GEN-LAST:event_numpad_2ActionPerformed

    private void numpad_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpad_3ActionPerformed
        // TODO add your handling code here:
        do_wyswietlacza("3");
    }//GEN-LAST:event_numpad_3ActionPerformed

    private void dotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dotActionPerformed
        // TODO add your handling code here:
        do_wyswietlacza(".");
    }//GEN-LAST:event_dotActionPerformed

    private void numpad_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpad_0ActionPerformed
        // TODO add your handling code here:
        do_wyswietlacza("0");
    }//GEN-LAST:event_numpad_0ActionPerformed

    private void dodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajActionPerformed
        // TODO add your handling code here:
        wybrane_dzialanie = "dodaj";
        nowe = true;
    }//GEN-LAST:event_dodajActionPerformed

    private void odejmijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odejmijActionPerformed
        // TODO add your handling code here:
        wybrane_dzialanie = "odejmij";
        nowe = true;
    }//GEN-LAST:event_odejmijActionPerformed

    private void mnozActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnozActionPerformed
        // TODO add your handling code here:
        wybrane_dzialanie = "mnoz";
        nowe = true;
    }//GEN-LAST:event_mnozActionPerformed

    private void dzielActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dzielActionPerformed
        // TODO add your handling code here:
        wybrane_dzialanie = "dziel";
        nowe = true;
        
    }//GEN-LAST:event_dzielActionPerformed

    private void wynikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wynikActionPerformed
        // TODO add your handling code here:
        dzialanie();
    }//GEN-LAST:event_wynikActionPerformed

    private void pmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmActionPerformed
        // TODO add your handling code here:
        wyswietlacz = (-1*Double.parseDouble(wyswietlacz))+"";
        refresh();
        
    }//GEN-LAST:event_pmActionPerformed

    private void ACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACActionPerformed
        // TODO add your handling code here:
        wyswietlacz = "0";
        CURRENT = 0;
        refresh();
        
        
    }//GEN-LAST:event_ACActionPerformed

    private void f_sinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_sinActionPerformed
        // TODO add your handling code here:
        wyswietlacz = Math.sin(Double.parseDouble(wyswietlacz)) + "";
        wybrane_dzialanie = "default";
        refresh();
    }//GEN-LAST:event_f_sinActionPerformed

    private void f_cosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_cosActionPerformed
        // TODO add your handling code here:
        wyswietlacz = Math.cos(Double.parseDouble(wyswietlacz)) + "";
        wybrane_dzialanie = "default";
        refresh();
    }//GEN-LAST:event_f_cosActionPerformed

    private void f_tanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_tanActionPerformed
        // TODO add your handling code here:
        wyswietlacz = Math.tan(Double.parseDouble(wyswietlacz)) + "";
        wybrane_dzialanie = "default";
        refresh();
    }//GEN-LAST:event_f_tanActionPerformed

    private void f_lnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_lnActionPerformed
        // TODO add your handling code here:
        wyswietlacz = Math.log(Double.parseDouble(wyswietlacz)) + "";
        wybrane_dzialanie = "default";
        refresh();
    }//GEN-LAST:event_f_lnActionPerformed

    private void f_expActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_expActionPerformed
        // TODO add your handling code here:
        wyswietlacz = Math.exp(Double.parseDouble(wyswietlacz)) + "";
        wybrane_dzialanie = "default";
        refresh();
    }//GEN-LAST:event_f_expActionPerformed

    private void f_invActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_invActionPerformed
        // TODO add your handling code here:
        wyswietlacz = 1/(Double.parseDouble(wyswietlacz)) + "";
        wybrane_dzialanie = "default";
        refresh();
    }//GEN-LAST:event_f_invActionPerformed

    private void f_factActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_factActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f_factActionPerformed

    private void f_cbrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_cbrtActionPerformed
        // TODO add your handling code here:
        wyswietlacz = Math.cbrt(Double.parseDouble(wyswietlacz)) + "";
        wybrane_dzialanie = "default";
        refresh();
    }//GEN-LAST:event_f_cbrtActionPerformed

    private void f_sqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_sqrtActionPerformed
        // TODO add your handling code here:
        wyswietlacz = Math.sqrt(Double.parseDouble(wyswietlacz)) + "";
        wybrane_dzialanie = "default";
        refresh();
    }//GEN-LAST:event_f_sqrtActionPerformed

    private void f_pow2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_pow2ActionPerformed
        // TODO add your handling code here:
        double k = Double.parseDouble(wyswietlacz);
        wyswietlacz = k*k + "";
        wybrane_dzialanie = "default";
        refresh();
        
    }//GEN-LAST:event_f_pow2ActionPerformed
    
    public void do_wyswietlacza(String n){
        if(nowe){
            CURRENT = Double.parseDouble(wyswietlacz);
            wyswietlacz = "";
            nowe = false;
        
        }
        
        if("default".equals(wybrane_dzialanie)){
            CURRENT = 0;
            wyswietlacz = n;
            wybrane_dzialanie = "dodaj";
        
        } else {
            wyswietlacz += n;
        }
        
        
        refresh();
        
    }
    
    public void dzialanie(){
        
        if("dodaj".equals(wybrane_dzialanie)){
            CURRENT += Double.parseDouble(wyswietlacz);
            wyswietlacz = CURRENT + "";
            
        }
        if("odejmij".equals(wybrane_dzialanie)){
            CURRENT -= Double.parseDouble(wyswietlacz);
            wyswietlacz = CURRENT + "";
           
        }
        
        if("dziel".equals(wybrane_dzialanie)){
            if("0".equals(wyswietlacz)){
                CURRENT = 0;
                wyswietlacz = "NaN";
                
            } else {
                CURRENT /= Double.parseDouble(wyswietlacz);
                wyswietlacz = CURRENT + "";
            }
            
            
        }
        
        if("mnoz".equals(wybrane_dzialanie)){
            CURRENT *= Double.parseDouble(wyswietlacz);
            wyswietlacz = CURRENT + "";
        
        }
        
        
    
        wybrane_dzialanie = "default";
        refresh();
    }
    
    
    public void refresh(){
        jLabel1.setText(wyswietlacz);
    
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Ustawienia ustawienia = new Ustawienia();
                new Panel(ustawienia).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AC;
    private javax.swing.JButton dodaj;
    private javax.swing.JTabbedPane dodatkowe_funkcje;
    private javax.swing.JButton dot;
    private javax.swing.JButton dziel;
    private javax.swing.JButton f_cbrt;
    private javax.swing.JButton f_cos;
    private javax.swing.JButton f_exp;
    private javax.swing.JButton f_fact;
    private javax.swing.JButton f_inv;
    private javax.swing.JButton f_ln;
    private javax.swing.JButton f_pow2;
    private javax.swing.JButton f_pown;
    private javax.swing.JButton f_show;
    private javax.swing.JButton f_sin;
    private javax.swing.JButton f_sqrt;
    private javax.swing.JButton f_tan;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToggleButton jToggleButton16;
    private javax.swing.JToggleButton jToggleButton17;
    private javax.swing.JToggleButton jToggleButton18;
    private javax.swing.JPanel klawiatura_funkcyjna;
    private javax.swing.JPanel klawiatura_podstawowa;
    private javax.swing.JButton mnoz;
    private javax.swing.JButton numpad_0;
    private javax.swing.JButton numpad_1;
    private javax.swing.JButton numpad_2;
    private javax.swing.JButton numpad_3;
    private javax.swing.JButton numpad_4;
    private javax.swing.JButton numpad_5;
    private javax.swing.JButton numpad_6;
    private javax.swing.JButton numpad_7;
    private javax.swing.JButton numpad_8;
    private javax.swing.JButton numpad_9;
    private javax.swing.JButton odejmij;
    private javax.swing.JButton pm;
    private javax.swing.JButton wynik;
    // End of variables declaration//GEN-END:variables
}
